FROM bitnami/pytorch

WORKDIR /app

# COPY requirements.txt .

# RUN pip3 install -r requirements.txt

# RUN apt-get update

# RUN apt-get -y install libgl1-mesa-glx

COPY . .

EXPOSE 8000

# CMD ["python", "server.py"]

